### PR TITLE
Fixes needed to build RPM package with Python 3

### PR DESCRIPTION
**Pull request by krig**
Two fixes needed to build the RPM package with Python 3.

### CODE REVIEW

**Comment by krig** [comment]
Hi Xin, I was able to run the regression test suite and saw some failures. I have pasted the results here:

https://gist.github.com/krig/e4ed6fc6b861658a8826b1838ca9ac5e

**Comment by liangxin1300** [comment]
OK, thanks!

**Comment by liangxin1300** [comment]
oh, krig, please create migration PR at https://github.com/liangxin1300/crmsh/tree/crmsh-py3
crmsh-py3 is the tree about py2->py3
crmsh-py3-newcommits is the tree just about crmsh's function, no relates with migration, but tested it on py3
I have picked above two commits of yours to crmsh-py3

**Comment by krig** [comment]
Ah, I see. Thank you

**Pull request merged**
